package data_structures.reinforcement_exercies

import data_structures.using_arrays.CaesarCipher
import kotlin.random.Random

/**
 * Give the next five pseudorandom numbers generated by the process described on
 * page 113, with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
 */

class R3_1 {
    companion object {
        private const val RANDOM_NUMBER_QUANTITY = 5
        fun pseudoRandom(a: Int, b: Int, cur: Int, n: Int) = (a * cur + b) % n

        @JvmStatic
        fun main(args: Array<String>) {
            val rand = Random
            for (i in 0 until RANDOM_NUMBER_QUANTITY) {
                println(rand.nextInt(this.pseudoRandom(12, 5, 92 ,100)))
            }
        }
    }
}


